name: CI/CD Pipeline Kelompok 1 (E-Commerce)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # === STAGE 1: CONTINUOUS INTEGRATION (TEST & QUALITY) ===
  test-code-quality:
    name: üß™ Test & Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath
          coverage: xdebug

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      # 1. Cek Kerapian Kode (PSR-12)
      - name: Check Code Style (PHPCS)
        run: ./vendor/bin/phpcs --standard=PSR12 app routes

      # 2. Analisis Statis (PHPStan)
      - name: Static Analysis (PHPStan)
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

      # 3. Security Audit
      - name: Security Audit
        run: composer audit

      # 4. Unit Testing (PHPUnit)
      - name: Run Tests
        run: php artisan test

  # === STAGE 2: CONTAINERIZATION (BUILD DOCKER) ===
  build-push-docker:
    name: üê≥ Build & Push Docker Image
    needs: test-code-quality # Hanya jalan jika tes berhasil
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Security Scan Image sebelum Push (Trivy)
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-kelompok1:latest
